FROM node:24.21.0-bookworm-slim@sha256:0e0ff40c39bc087845bfb27465a0df4ea419520094bc35842ff83dd8cbe6f9b6
WORKDIR /workspace
COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund && chown node:node /workspace
COPY --chown=node:node scripts ./scripts
USER node
CMD ["node", "scripts/generate-postman.mjs"]
